server:
  port: 8888
  
spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  profiles:
    active: native 
  cloud:
    config:
      server:
        native:
          search-locations: file:\\\${user.home}\native-repo
        git:
          uri: https://github.com/mincoln419/spring-cloud-config
          #username:[mincoln419]
          #password:[]
#          uri: file:\\\C:\SpringCloud\config-repo

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httptrace, busrefresh