spring: 
  h2:
    console: 
      enabled: true
      
jpa:
  open-in-view: false
  hibernate:
    ddl-auto: create-drop
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    use-new-id-generator-mappings: false
  show-sql: true
  properties:
    hibernate: 
      enable_lazy_load_no_trans: true  
      format_sql: true

jackson:
  serialization:
    fail-on-empty-beans: false


logging:
  level: 
    root: debug

