FROM openjdk:11
VOLUME /tmp
EXPOSE 8080
ARG JAR_FILE=service-0.0.1-SNAPSHOT.jar
ADD ${JAR_FILE} clickping-api.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/clickping-api.jar"]