server: 
  port: 9001

spring: 
  application:
    name: discoveryservice

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    severice-url: 
      defaultZone: http://127.0.0.1:8761/eureka
      
